---
- hosts: hw1
  become: yes
  vars:
    document_root: /var/www/html
    app_root: ~/CSE356/hw0
  tasks: 
    - name: Install nginx
      apt: 
        name: nginx
        state: latest
        update_cache: yes

    - name: Clone site files
      git:
        repo: https://github.com/pollsmor/CSE356.git
        dest: ~/CSE356/
        clone: yes
        update: yes

    - name: Copy site files to document root
      copy:
        src: "{{ app_root }}"
        dest: "{{ document_root }}"
        remote_src: true
        mode: preserve

    - name: Copy Nginx template to sites-available
      copy:
        src: "{{ app_root }}/server.conf"
        dest: /etc/nginx/sites-available/
        remote_src: true

    - name: Enable new site
      file:
        src: /etc/nginx/sites-available/server.conf
        dest: /etc/nginx/sites-enabled/default
        state: link

    - name: Restart nginx
      service:
        name: nginx
        state: restarted

    
    